import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      <header className="container mx-auto px-4 py-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold">
          <span className="text-blue-600">Study</span>Sphere
        </h1>
        <div className="flex gap-4">
          <Link href="/login">
            <Button variant="ghost">Sign In</Button>
          </Link>
          <Link href="/register">
            <Button>Get Started</Button>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-20 text-center">
        <h2 className="text-5xl font-bold tracking-tight text-gray-900 sm:text-6xl">
          Your AI-Powered
          <br />
          <span className="text-blue-600">Study Companion</span>
        </h2>
        <p className="mt-6 text-lg leading-8 text-gray-600 max-w-2xl mx-auto">
          Transform your study materials into personalized learning resources.
          Upload PDFs, get AI-generated summaries, flashcards, quizzes, and
          track your progress.
        </p>
        <div className="mt-10 flex items-center justify-center gap-4">
          <Link href="/register">
            <Button size="lg" className="text-lg px-8 py-6">
              Start Learning Free
            </Button>
          </Link>
        </div>

        <div className="mt-24 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
          <div className="p-6 rounded-xl bg-white shadow-sm border">
            <div className="text-3xl mb-4">📄</div>
            <h3 className="font-semibold text-lg">Smart Upload</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Upload PDFs or paste text. We extract and organize your content automatically.
            </p>
          </div>
          <div className="p-6 rounded-xl bg-white shadow-sm border">
            <div className="text-3xl mb-4">🧠</div>
            <h3 className="font-semibold text-lg">AI Study Packs</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Get summaries, flashcards, quizzes, and topic breakdowns generated by AI.
            </p>
          </div>
          <div className="p-6 rounded-xl bg-white shadow-sm border">
            <div className="text-3xl mb-4">📊</div>
            <h3 className="font-semibold text-lg">Track Progress</h3>
            <p className="text-gray-600 mt-2 text-sm">
              Identify weak areas, take adaptive quizzes, and watch your understanding grow.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
